### ISSUE TITLE
Game crashes once u step onto a conveyor belt (immersive engineering)

### ISSUE THREAD

**Issue by LiveYourLifeNerd** [czbuendel/EL2Test#101]
Modpack Version: v1.04 i think (Latest is not a version number)

**Describe the bug**
Once you jump or step onto a immersive engineering conveyor belt your game WILL crash.

**To Reproduce**
Make a conveyor belt, try making a metal press, finish it -> can't make it into a metal press -> jump onto belt and crash ur game

**Expected behavior**
Conveyor belt pushes me off or nothing happens.

**Log Files**
Deleted everything cause i lost 2 worlds to this dumb bug.

**Comment by czbuendel** [comment]
Repeat of https://github.com/Engineers-Life/EL2/issues/98
