### ISSUE TITLE
Immersive Engineering / Tetra bug

### ISSUE THREAD

**Issue by DreiPixel** [czbuendel/EL2Test#102]
Already posted this on Immersive Engineerings github.
https://github.com/BluSunrize/ImmersiveEngineering/issues/4858

but basically:
Tetra causes a Bug when you step on a conveyor belt and makes player disconnect.
Tetra needs to be updated to fix that.

**Comment by czbuendel** [comment]
Please check the pins before posting issues. https://github.com/Engineers-Life/EL2/issues/98
