### ISSUE TITLE
The Mining Dimension Teleporter is uncraftable

### ISSUE THREAD

**Issue by FinnishCrusader** [czbuendel/EL2Test#103]
![image](https://user-images.githubusercontent.com/67581566/122638719-7188e680-d0fe-11eb-9743-aa0ede3bbdf3.png)

**Comment by czbuendel** [comment]
![image](https://user-images.githubusercontent.com/23238026/122730484-e152ba80-d23f-11eb-905f-aecd9a0a8d0f.png)
![image](https://user-images.githubusercontent.com/23238026/122730531-ee6fa980-d23f-11eb-96c3-54de84820c18.png)

And you blatantly ignored the issue template. Closed and locked.
