### ISSUE TITLE
Iron Saw in Quest Not Working

### ISSUE THREAD

**Issue by joshpro8423** [czbuendel/EL2Test#104]
The iron saw you make in the quest has no recipe to be used to cut any wood into planks/sticks as the quest states, only anvil recipes as well as arc furnace salvaging recipes

**Comment by czbuendel** [comment]
Sorry about that, that saws should be there anymore or be able to be crafted. Just complete the quest by cheating that saw in.

Fixed the quest in https://github.com/Engineers-Life/EL2/commit/90b0924ebebaf4d90af79ce4e6bb09fa498bce77
