### ISSUE TITLE
Conduit Quest Enchanted book is unclear

### ISSUE THREAD

**Issue by Benjamin-Berry** [czbuendel/EL2Test#106]
Modpack Version: 1.0.4

**Describe the bug**
The enchanted book required in the Conduit Quest is apparently Depth Strider III. There is no way for the player to tell.

**To Reproduce**
Mouse over the book in the quest ui.

**Expected behavior**
Book to say what enchantment is required.

**Comment by czbuendel** [comment]
Oh I am sorry about that, that was supposed to be a reward for that quest not a requirement. *facepalm*

I will fix that for the next release.
