### ISSUE TITLE
Warnings about recipe names

### ISSUE THREAD

**Issue by dr3ams** [czbuendel/EL2Test#108]
Modpack Version: 1.05

[WARNING] A recipe with the name 'food.item.vfp.dough_ball' already exists and will be overwritten: this is most likely an error in your scripts
[WARNING] A recipe with the name 'minecraft.charm.minecraft.bone' already exists and will be overwritten: this is most likely an error in your scripts
[WARNING] A recipe with the name 'minecraft.charm.vanillafoodpantry.dough_ball' already exists and will be overwritten: this is most likely an error in your scripts

**Comment by D0CTOR-ZED** [comment]
Changed removal of fried dough to remove it from the four means of cooking it. (https://github.com/Engineers-Life/EL2/commit/3d7cae8866f12f04752113fb66e782985923f145)
Disabled smelting bones into bone meal in the quark config to remove bone conflict. (https://github.com/Engineers-Life/EL2/commit/4f4f72338b63e7f69085e5ac188741f848cf6db3)
