### ISSUE TITLE
Ender Bee Crash

### ISSUE THREAD

**Issue by DreiPixel** [czbuendel/EL2Test#109]
Modpack Version: 1.05

**Describe the bug**
Ender bee will crash the server

**To Reproduce**
go to nether and find a enderbee and crash

**Expected behavior**
no crash

**Fix**
https://github.com/JDKDigital/productive-bees/issues/193
Update forge to 1.16.5-36.1.23 as this is the required version for productive bees. no idea why minecraft starts fine without the required version.

**Comment by czbuendel** [comment]
This can be fixed by updating Productive Bees to 0.6.9.15.

This will be included in the next pack update but is safe to update to at any time if the issue arises for anyone in 1.05.

Closing and pinning this issue till the next update.

**Comment by czbuendel** [comment]
We will also look into updating forge in the next version to a more recent version.
