### ISSUE TITLE
Server Error - "Incomplete set of tags received from server. Please contact server operator."

### ISSUE THREAD

**Issue by gabrielebiolo** [czbuendel/EL2Test#110]
Modpack Version: Lastest (1.05)

After downloading the server pack and following the first steps on my local machine I uploaded the pack to the server I purchased, I set everything up to perfection and trying to enter the server for the first time it gives me an error which is the following : "Incomplete set of tags received from server. Please contact server operator." I tried restarting the server and renaming the server .jar (as read on google) but was unsuccessful. Also I read on google that it could be a problem regarding the server side mods but I uploaded all the mods I had downloaded and even comparing they are all present. I also noticed that on the server console it seems to let me in and then disconnects me. I have no idea how to proceed, any help is welcome. Thank you.

1. Download server pack for 1.05
2. First setup on local machine (accept EULA, launch .BAT)
3. Upload everything on server
4. Start server and join from client

The last thing I'm going to try right now is to accept the eula and upload to the server without running the .bat but I don't think it can work.

**Comment by gabrielebiolo** [comment]
Update: I just finished trying to do what I wrote before, no results, everything stayed the same.

**Comment by gabrielebiolo** [comment]
Update: I just finished making other attempts, I tried to host it locally and it gives me the same error. Even trying with version 1.04 nothing changes.

**Comment by D0CTOR-ZED** [comment]
Just downloaded the 1.05 server pack, started a server and join it without issue.  Something must have gone wrong in your install, either on the server or the client.  If you are using the curseforge launcher, consider trying another launcher.  GDLauncher is recommended.

**Comment by gabrielebiolo** [comment]
I downloaded GDLauncher and the modpack. Even with this it keeps giving the same error, both locally and server. I don't understand why it doesn't work, my friends also tried to join and keeps giving the error to them too. At this point I doubt it's client-side file corruption. It also seems strange to me that the server files are corrupt because I downloaded/used 3 different server packs.

**Comment by gabrielebiolo** [comment]
**Update:** I changed the .jar to be started by the server (for those who will read: Attention! The server has to start the forge.....jar not minecraft_server.....jar) and also the java version of the server, now when I am on the server list on "multiplayer" there is an X indicating that the modpack is not the same or not compatible however the server works and is stable. I will try to fix this last bug by changing the server side version of java one last time.

Thanks for your help @D0CTOR-ZED
