### ISSUE TITLE
[Suggestion] Add Framed Drawer for more customisable Drawer

### ISSUE THREAD

**Issue by Pinguin34** [czbuendel/EL2Test#113]
I suggest to add Framed Drawer for getting customisable drawer in the modpack

**Comment by czbuendel** [comment]
Unless you are suggesting a mod that can do that we can't help you.

**Comment by D0CTOR-ZED** [comment]
Unfortunately, the framed drawers aren't in the 1.16 version of the storage drawers mod.

**Comment by Pinguin34** [comment]
Framed drawer it's a mod who are in 1.16 https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers
I use it on another modpack in 1.16.5
