### ISSUE TITLE
Add Create Mod

### ISSUE THREAD

**Issue by maca134** [czbuendel/EL2Test#114]
Create is a pretty nice immersive mod which seems to fit well with the mod pack theme.
https://www.curseforge.com/minecraft/mc-mods/create

**Comment by czbuendel** [comment]
Create is a fantastic mod! But, it has no current plans to be added to EL2.

Create is very free-form in the utilization of its machines which makes it hard to supply it with quests appropriate for a questing pack like EL2. Another reason it is not under current consideration is that it has much overlap in its machines functions with Immersive Engineering for industrial purposes, which is the focus of the pack. If at a time in the future it can be worked out how to integrate it into the pack without stepping on other mods functions it will be considered.
