### ISSUE TITLE
My game crashes when opening my world

### ISSUE THREAD

**Issue by Eraya02** [czbuendel/EL2Test#115]
Modpack Version: EL2-1.16.5-1.04

**Describe the bug**
I Cant load my world without crashing

**To Reproduce**
1. play the modpack
2. start immersive enigneering
3. start making a metal press
4. go get your hammer in a chest 
5. walk back to your machine
6. game crashes when facing alloy kiln

**Expected behavior**
Game does not crash

**Screenshots**
I dont have any, i cant open my world anymore

**Log Files**
[latest.log](https://github.com/Engineers-Life/EL2/files/6843400/latest.log)

Thx for your help, i really enjoyed the modpacks.

**Comment by czbuendel** [comment]
There is no crash in that latest log file.

**Comment by czbuendel** [comment]
Sounds like you most likely stepped on a conveyor belt. Which was fixed in V 1.05. You should update as you are 2 pack updates out of date (1.06 is current).

**Comment by czbuendel** [comment]
https://github.com/Engineers-Life/EL2/issues/98 for more info.

**Comment by Eraya02** [comment]
I updated my game to 1.6 and I can play again!
Thx for the help!!!!

I really enjoy the modpack, Well done.
