### ISSUE TITLE
Is there any way to get the Infinity Backpack?

### ISSUE THREAD

**Issue by Guardian9978** [czbuendel/EL2Test#116]
**Is your feature request related to a problem? Please describe.**
I'm trying to craft the Infinity Backpack but am unable to craft either the Common Black Hole Unit it or the Common Black Hole Tank it requires.
It appears the you disabled the recipes for both the Common Black Hole Unit and the Common Black Hole Tank.

**Describe the solution you'd like**
A means to be able to craft the Infinity Backpack.

**Describe alternatives you've considered**
Disabling the Infinity Backpacks recipe if crafting it isn't what you want in your modpack.

**Additional context**
None that I can think of.

**Comment by czbuendel** [comment]
No. All the infinity crap is disabled for a reason as they make no logical sense.
He keeps trickling items out in updates and we missed it.

IF is primarily for automated farming and ranching less a few other minor items (mob grinder and the lazer drill which should probably be just disabled.) If there was another automated farming mod for 1.16 available we would switch to it quickly and drop IF.
