### ISSUE TITLE
Netherite Scrap not produced after processing Ancient Comb in Powered Centrifuge

### ISSUE THREAD

**Issue by AndrewR73** [czbuendel/EL2Test#117]
Modpack Version: 1.06

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.
Not installed

**WE DO NOT PROVIDE SUPPORT TO HEAVILY MODIFIED MODPACKS. OUR PACK IS CURATED FOR WORKABILITY AND NO CONTENT OVERLAP, NOT ADDING ADDITIONAL MODS TO.**

**Describe the bug**
The Ancient Comb, produced from the Ancient Bee, produces no Netherite scrap when processed by the Powered Centrifuge. A powered centrifuge by itself, no output connections, only being provided power, will slowly process the Ancient Comb, but when the arrow completes, the comb is gone and no scrap is in the inventory of the centrifuge... just gone. Level of honey in the Powered Centrifuge appears to have no effect

All other combs (Coal, Iron, Diamond, Gold, Aluminum, etc.) produce the output as seen in JEI.

**To Reproduce**
1 - Steps to reproduce the behavior:
2 - Craft a Powered Centrifuge
3 - Place an Ancient Comb in the Powered Centrifuge
4 - Wait for comb to be processed
5 - Observe comb get consumed yet no scrap in Centrifuge's inventory

**Expected behavior**
An Ancient Comb is processed by the Powered Centrifuge and one Netherite Scrap is produced, along with a little honey, as shown in JEI.

**Screenshots**
Here are three screenshots... (Minecraft day timestamp at the right side)
Before:
![EL2 - PwrCtfg Before](https://user-images.githubusercontent.com/8558973/127383236-1e0f78b9-261a-44ff-8cd2-e8f395ded0f9.png)
During:
![EL2 - PwrCtfg During](https://user-images.githubusercontent.com/8558973/127383239-741aff86-59b7-49b4-93c5-73cb5c804ef0.png)
After:
![EL2 - PwrCtfg After](https://user-images.githubusercontent.com/8558973/127383233-4b373c02-f658-49d6-b557-421f870ad2ab.png)
It can be seen the centrifuge has power, processed a Quartz comb just fine, is processing an Ancient Comb, but after processing, no scrap is in the Inventory.

**Log Files**
N/A

**Comment by czbuendel** [comment]
https://github.com/JDKDigital/productive-bees/issues/201#issuecomment-888572839
