### ISSUE TITLE
Client Crash upon trying to break IE Feedthrough Insulator

### ISSUE THREAD

**Issue by ThisIsNotMe1612** [czbuendel/EL2Test#118]
Modpack Version: 1.06[1.16.5]

Optifine was installed when error first occured, Has since been uninstalled and error persists.
No other modifications of the pack have been made.

**Describe the bug**
After placing and forming an Immersive Engineering Feedthrough Insulator from LV Wire Connectors i tried to break it again, but as soon as i click the left mouse button the game crashes.

**To Reproduce**
1. Place LV Wire Connector on opposing sides of a block
2. Right click one of them with engineers hammer
3. try to break any part of the multiblock

**Expected behavior**
The block should break

**Screenshots**
The client crashes to desktop

**Log Files**
https://gist.github.com/ThisIsNotMe1612/d942a0c6063c60599f64f36077dfdfbd#file-crash-2021-07-29_17-54-37-client

**Comment by czbuendel** [comment]
You should probably forward this to the IE devs on their issue tracker. Not much we are able to do on this front.

**Comment by ThisIsNotMe1612** [comment]
I see. Will do.

Great Pack btw.
