### ISSUE TITLE
Unable to see any requirements in the Glossary of the Project MMO menu, and backpack does not come up. 

### ISSUE THREAD

**Issue by Mwolfe0820** [czbuendel/EL2Test#119]
Modpack Version: #### (1.06)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**WE DO NOT PROVIDE SUPPORT TO HEAVILY MODIFIED MODPACKS. OUR PACK IS CURATED FOR WORKABILITY AND NO CONTENT OVERLAP, NOT ADDING ADDITIONAL MODS TO.** 
(only running basic Engineer's Life 2 modpack)

**Describe the bug**
This did not always happen with the backpack because I was able to access it in the beginning but I have noticed recently my "B" key is not bringing up the backpack even though it is in the backpack slot and i checked my controls and "B" is still the hotkey for it. Within the Project MMO menu, I am able to see everything until I get into the glossary and try and click on anything with "requirements" in the name. 

**To Reproduce**
1. Start up game
2. Press "P" to enter the Project MMO menu
3. Click on "Glossary"
4. Click on any of the 5-6 options labeled "requirements" 
5. See blank page

**Expected behavior**
I was expecting to see what level in what category is required to craft a certain item or mine certain materials, etc. 

**Screenshots**

**Log Files**
Pack is not crashing.

**Comment by czbuendel** [comment]
That is because nothing is locked behind any requirements. 

As far as the backpack key issue it may be a game desync possibly. Can't really know anything without logs.

**Comment by D0CTOR-ZED** [comment]
As far as the "B" key, check your keybinds.  It is possible that a mod (such as Build Guide), was added that also uses that key.  Or, perhaps, something like the tetra tool belt keybind didn't conflict until you had a tool belt.

**Comment by czbuendel** [comment]
Closing because no reply.

**Comment by strepito66** [comment]
i have the same issue now, but I can't use the iron mattock
