### ISSUE TITLE
Game crash when opening chests

### ISSUE THREAD

**Issue by Calou42** [czbuendel/EL2Test#120]
Modpack Version: EL2 - 1.06 

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**WE DO NOT PROVIDE SUPPORT TO HEAVILY MODIFIED MODPACKS. OUR PACK IS CURATED FOR WORKABILITY AND NO CONTENT OVERLAP, NOT ADDING ADDITIONAL MODS TO.**

**Describe the bug**
When i try to pickup an item in the chest , the game crash .

**To Reproduce**
1. Go to open the game
2. Click on a chest and try to take an item
3. Scroll down 

**Expected behavior**
I want to take my food or my ore and it's impossible.

**Screenshots**
Sorry , impossible to take a screenshot .

**Log Files**
https://gist.github.com/Calou42/2cdd7940117c61a861ff6c0a9eabb4fe

**Comment by D0CTOR-ZED** [comment]
I believe this is a Terra Incognita issue which they are aware of, so should be fixed with their next update.  If you have a basket in your inventory, removing the basket from your inventory should prevent the crash.

**Comment by Calou42** [comment]
Thanks Docteur Zed but i decide to remove my game and restart a new world ;)

Probably your answer can help anyone :)
