### ISSUE TITLE
Tetra aeternium bowlimbs are uncraftable

### ISSUE THREAD

**Issue by ThisIsNotMe1612** [czbuendel/EL2Test#121]
Modpack Version: 1.06

I am currently trying to add a bow limb made from Aeternium to my existing bow. However, the GUI of the Workbench tells me, that would require a tier 9 hammer. I can not find any material that would allow me to craft a Hammer of that tier in the holosphere and the forge hammer only goes up to tier 7 with combustion chamber upgrades.

1. open a tetra workbench
2. place a bow inside
3. select bow limb to craft
4. place aeternium ingots in material slot

**Expected behavior**
The tier should be 7 or lower or Aeternium should not be listed as a valid material for bow limbs

May be relevant: all other parts i have checked only take a tier 6 hammer to craft.

**Comment by czbuendel** [comment]
This isn't a change implemented by us, this is done by Tetranomicon.
