### ISSUE TITLE
Oak planks on Pattern while sneaking

### ISSUE THREAD

**Issue by Pinguin34** [czbuendel/EL2Test#122]
When I sneaking t osee craft in pattern, the craft with the pattern display me a oak planks instead of a pattern

![2021-08-14_09 24 56](https://user-images.githubusercontent.com/82638188/129438704-3c832436-96b3-4963-8a62-e1e8050b72de.png)

![2021-08-14_09 24 58](https://user-images.githubusercontent.com/82638188/129438705-492e66eb-8234-456f-8b5a-02e21ba0ad74.png)

**Comment by D0CTOR-ZED** [comment]
This is a refined storage issue and is outside the scope of what we can do with a pack.  You can search here (https://github.com/refinedmods/refinedstorage/issues) to see if it has already been reported.  I did see some related issues, so there is a good chance that they would resolve this issue when those are fixed.
