### ISSUE TITLE
Random Teleportation

### ISSUE THREAD

**Issue by Pinguin34** [czbuendel/EL2Test#123]
Modpack Version: 1.07 

I got a few teleportation since I'm updated on 1.07. I don't know if it's a bug, or a feature of enderman / ender bees.

**Comment by D0CTOR-ZED** [comment]
Sounds like it might be something tetra let's endermen do to you when you are using an end rod as part of your tool.  I can't confirm this, but check your tools and maybe change out the end rods or stash them in a backpack to see if that fixes the issue.

**Comment by Pinguin34** [comment]
Oh! I totally forget this. I gonna try this so
