### ISSUE TITLE
Better power generation and transfer

### ISSUE THREAD

**Issue by Cloudninjakip** [czbuendel/EL2Test#124]
**Is your feature request related to a problem? Please describe.**
There's massive reactors, and yet there's only low RF rate cables to transfer it all.

**Describe the solution you'd like**
Add enderio/rftools for transferring power, due to IE not meeting the transfer requirements of the nuclear reactors

**Describe alternatives you've considered**
Anything more than IE for transferring power between generators and machines. Something like flux networks would definitely help, but might not fit the balance of the pack very smoothly.

**Additional context**

**Comment by czbuendel** [comment]
As currently there are no machines that actually take larger amounts of power we really are not worried about it. 

We are looking into mods for future updates that will require more power and will update accordingly then.

**Comment by Cloudninjakip** [comment]
From what I've heard, the arc furnace in IE consumes more power than the hv cables can transfer, if you have more than one item in them at once
