### ISSUE TITLE
Quest Descriptions

### ISSUE THREAD

**Issue by Nekosity12** [czbuendel/EL2Test#125]
**Is your feature request related to a problem? Please describe.**
If you consider a lack of information a problem then yes but I assume you mean more so a bug? In which case no.
**Describe the solution you'd like**
Descriptions added to sunflower seeds, cumin seeds and quinoa seeds that describe how you obtain them. Sunflower seeds are crafted with 3 sunflowers, cumin seeds drop from a flower not grass and cannot be bought in the market and quinoa seeds also drop from a flower and cannot be bought in the market.
**Describe alternatives you've considered**
Nothing, the above feels easy enough unless you'd consider removing the quests but I doubt that will be considered :P
**Additional context**
Unfortunately my computer is too much of a potato to take screenshots during the game else I'll likely freeze then crash due to lack of memory (Only 4 gb ram max here Dx)

**Comment by czbuendel** [comment]
1. JEI would have given you the first recipe for sunflower seeds.
2. Both of those are just exploration rewards. I will update their descriptions with some info.
