### ISSUE TITLE
Cannot install (child addon 349530)

### ISSUE THREAD

**Issue by Drake630** [czbuendel/EL2Test#126]
Modpack Version: 1.07 (Latest is not a version number)

**Describe the bug**
Trying to download the modpack via curse launcher and getting the same error every time. 

Error: Cannot find child addon: 349530

**To Reproduce**
1. Open Curseforge
2. Search Engineer's Life 2
3. Click install
4. Tries to install but stops at around 92/177 mods installed and produces error from above.

**Expected behavior**
Expected to have full install and be able to play.

**Comment by czbuendel** [comment]
Curseforge is having issue, you most likely will have to wait for curse to stabilize out and downloads should work again.
