### ISSUE TITLE
Woodcutter can't create oak planks (and other oak recipes)

### ISSUE THREAD

**Issue by ambentzen** [czbuendel/EL2Test#128]
Modpack Version: 1.07

**Describe the bug**
When putting oak logs in the woodcutter the list of output is limited compared to other types of logs.
All the other types of planks are possible.

**To Reproduce**
1. Add oak log in input slot of woodcutter
2. Possible output is limited 

**Expected behavior**
You should be able to create oak planks in the woodcutter.

**Comment by czbuendel** [comment]
https://github.com/Engineers-Life/EL2/issues/129
Posted solution in the above issue.
