### ISSUE TITLE
1.07 Missing Recipe Files (Planks, Gears, and Foundations)

### ISSUE THREAD

**Issue by czbuendel** [czbuendel/EL2Test#129]
Modpack Version: 1.07

A number of recipes were broken or missing in the 1.07 pack update.

For Oak planks the following script file can be placed in your instance (in the script folder, let it rewrite the existing file)
[planks.zip](https://github.com/Engineers-Life/EL2/files/7025988/planks.zip)

The following script will fix the Industrial Foregoing gear recipe from being missing. (allow it to replace in the script folder)
[IE.zip](https://github.com/Engineers-Life/EL2/files/7025993/IE.zip)
You also may want to update your installed version of Industrial Foregoing as its manual recipe is missing as well and fixed in newer versions of the mod that came out after the pack updated.

This final script fixes the foundations not translating between version properly. (allow it to replace in script folder)
[MM.zip](https://github.com/Engineers-Life/EL2/files/7025999/MM.zip)

Big thanks to Zed for all the quick script fixes.

**Comment by JonasDoe** [comment]
Not sure this issue covers it, so just to be sure: diamond gears aren't craftable at the moment, blocking all pathes into advanced technology. Would be great if you could fix that!

**Comment by Porcy** [comment]
Might be related, but Black Hole Tanks (all tiers) aren't craftable either :(

**Comment by czbuendel** [comment]
Closing as the pack was updated.
