### ISSUE TITLE
Crafting 

### ISSUE THREAD

**Issue by Gunner76th** [czbuendel/EL2Test#131]
Modpack Version: 1.07 (Latest is not a version number)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**WE DO NOT PROVIDE SUPPORT TO HEAVILY MODIFIED MODPACKS. OUR PACK IS CURATED FOR WORKABILITY AND NO CONTENT OVERLAP, NOT ADDING ADDITIONAL MODS TO.**

**Describe the bug**
When trying to craft the wicker basket made from Swamp Reed, the game crashes. This is on 1.07 using GDLauncher with no modifications. 

**To Reproduce**
1. Collect swamp reeds
2. Open Crafting Table
3. Place reeds in crafting table in same formation as trying to make a boat, only it is suppose to make a basket
4. Watch as your client locks up then crashes

**Expected behavior**
I expect to be able to craft the basket without my client crashing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5566872/130672682-f7976a1c-2b93-49f0-ba09-e530f8f9f89f.png)

**Log Files**
[crash-2021-08-24_14.29.42-client.txt](https://github.com/Engineers-Life/EL2/files/7041450/crash-2021-08-24_14.29.42-client.txt)
[crash-2021-08-24_14.41.07-client.txt](https://github.com/Engineers-Life/EL2/files/7041451/crash-2021-08-24_14.41.07-client.txt)
[crash-2021-08-24_14.48.31-client.txt](https://github.com/Engineers-Life/EL2/files/7041469/crash-2021-08-24_14.48.31-client.txt)
[latest.log](https://github.com/Engineers-Life/EL2/files/7041470/latest.log)
[debug.log](https://github.com/Engineers-Life/EL2/files/7041471/debug.log)

***Note*** 

If you use the Shift Click method for crafting the basket it works. If you attempt to manually place each reed in the crafting grid is when it crashes. However, opening your inventory and clicking on reeds that you have while the basket is also in your inventory will cause your client to crash.

**Comment by Azmalent** [comment]
Hey, I'm the dev of Terra Incognita. This issue is a conflict with newer versions of Quark, which was fixed in the new beta. You just need to update the mod to fix this.

**Comment by czbuendel** [comment]
Issue solved above.
