### ISSUE TITLE
Currency exchange quests are non repeatable.

### ISSUE THREAD

**Issue by ImelchorI** [czbuendel/EL2Test#132]
Are you supposed to be able to complete them? I just started playing the modpack and traded a wooden coin for a stack of cobble.

Now the quest is marked with a green checkmark and i cant trade further coins for cobble.

I was under the impression youre supposed to be able to keep trading wooden coins for stacks of cobble for building and crafting like in other modpacks that use a quest currency system.

**Comment by czbuendel** [comment]
Currently no. There is no normal way to handle repeatable quests with FTBQuests.
