### ISSUE TITLE
Flax harvesting

### ISSUE THREAD

**Issue by sauphle** [czbuendel/EL2Test#135]
**Is your feature request related to a problem? Please describe.**
Flax cannot be harvested like regular double tall crops. When you harvest it (bottom part or top part) it does not replant its seed.

**Describe the solution you'd like**
When you harvest fully grown flax crop it plants the crop where you harvested it while consuming a seed

**Describe alternatives you've considered**
Have the top part be separate from the bottom and breaking the top would keep the bottom safe, like industrial hemp

**Comment by czbuendel** [comment]
That is nothing we can do, report it to the mod author.
