### ISSUE TITLE
A tool to measure RF output of blocks.

### ISSUE THREAD

**Issue by ImelchorI** [czbuendel/EL2Test#136]
The fact there IE doesnt have a tool to measure power flowing through lines, or even output out of generators is insanely frustrating.

The engineers volt meter only displays the charge level of certain blocks like capacitors, machines and wire connectors, but not how much energy is being produced or transported through power lines.

Since transfer limits and the possiblity of wires burning up is a mechanic that exists in the mod, aswell as variable output of basic generators dependent on weather conditions, or simply the setup which you build them (water wheels, thermoelectric generators), there is little possiblility of experimenting how to get optimal power production out of your generators or if you have made a mistake somewhere, if you cant measure the exact values at which the generators are producing power.

Please, this pack needs at least a measuring instrument that allows us to measure the power output of the generators somehow.

**Comment by czbuendel** [comment]
We. Are. Not. The. Mod. Authors.

If you have a mod to suggest then suggest it.

Also there is a block to measure RF rate, it is the Current Transformer.
There is literally a quest for it.
![image](https://user-images.githubusercontent.com/23238026/132255054-c5b14d8a-3e59-4282-b0c4-548a9118f492.png)

**Comment by ImelchorI** [comment]
thank you.

i wasnt asking for you to make a mod btw. but there had to already be an existent one that could do it. 

i didnt know the current transformer put out a reading of the power flow, and just thought it only converted between different power levels (HV to MV etc.)

ive overlooked the flow rate readout on the block, srry, my bad.

(i didnt just immediately come here either btw. i tried to look this up first, and every thread i found oline talked about using ender io capacitors or something similar from other mods, none of them mentioned IE's solution itself. so it looked like there wasnt anything in IE itself.)

**Comment by czbuendel** [comment]
I wish we had Ender IO, I really like the capacitor readouts. 

Yeah the current transformer is kind of a bad name, the one that actually steps between levels has a relatively similar name.

Just hook up you wires to it and you should be able to right click and track the power flowing through it.

**Comment by ImelchorI** [comment]
Yea, thats a huge help, thank you.
