### ISSUE TITLE
Immersive Engineering Excavator - Break the World / Crash

### ISSUE THREAD

**Issue by SD-ITLab** [czbuendel/EL2Test#140]
Modpack Version: #### (Latest is not a version number)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**WE DO NOT PROVIDE SUPPORT TO HEAVILY MODIFIED MODPACKS. OUR PACK IS CURATED FOR WORKABILITY AND NO CONTENT OVERLAP, NOT ADDING ADDITIONAL MODS TO.**

**Describe the bug**
World Break with Building a Immersive Engineering Excavator.

**To Reproduce**
1. Build Excavator
2. click with the Engineer's Hammer on it to change.
3. Game crashing instant, and can´t reloading the world. 
    Server Crashing.
4. Only fixing with Delete the excavator with World edit programm.
5. See error

**Expected behavior**
Change to worked Excavator without crash.

**Log Files**
If the pack is crashing please provide the latest.log from the logs folder of your instance. Use https://gist.github.com to create a link to share the log.

Log and Crash report:

Crash
https://gist.github.com/TrelLyX/bd731348bb0f8d8bdda11dc3cbe67f39

Log
https://gist.github.com/TrelLyX/2c1b6a36257f96afcf97a697e2700e33

**Comment by czbuendel** [comment]
https://github.com/Engineers-Life/EL2/issues/77
