### ISSUE TITLE
Seagulls can steal Lunchboxes

### ISSUE THREAD

**Issue by joscha999** [czbuendel/EL2Test#146]
Modpack Version: 1.09

**Describe the bug**
Alex's mobs seagulls can steal whole lunchboxes from your inventory - see https://github.com/Alex-the-666/AlexsMobs/issues/631 as reference

**To Reproduce**
1. Get lunchbox
2. Go near beach and let a seagull steal it

**Expected behavior**
Seagulls should not be able to steal whole lunchboxes.

**Screenshots**

**Log Files**

**Comment by dr3ams** [comment]
Disabled in 1.11
