### ISSUE TITLE
Typo in quest book

### ISSUE THREAD

**Issue by jocker-il** [czbuendel/EL2Test#150]
Modpack Version: 1.09

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable. - n/a

**Describe the bug**
See screenshot below - used the word 'lust' instead of 'must'

**To Reproduce**
Steps to reproduce the behavior: -n/a

**Expected behavior** -n/a

**Screenshots** 

![BumbleBee_Rodeo](https://user-images.githubusercontent.com/13031901/147371128-7cfb3aab-a530-457d-8600-cabe60d45ea1.JPG)

**Log Files** -n/a

**Comment by dr3ams** [comment]
fxd
