### ISSUE TITLE
[CRASH - 1.16.5] duplicate mods cause mixin crash

### ISSUE THREAD

**Issue by KhanhPham05** [czbuendel/EL2Test#153]
Modpack Version: 1.13

**Describe the bug**
Duplicate mod in the pack modlist, which cause a crash during mod construction

**Additional Mods**:
[mainly performance mod]
+ LazyDFU, Magnesium (Extras as well)
+ NO OFTIFINE

**To Reproduce**
1. Update Backpacked in the mod list (somehow it is 1.16.3)
2. launch the pack __in curseforge app__

**Screenshots**
![image](https://user-images.githubusercontent.com/68932626/157855614-4fe7348d-18c2-49df-a7ba-f0fb361c134e.png)

**Log Files**
https://gist.github.com/KhanhPham05/e34c1bf29a6f577c0c5d3ea3e1a8cea7

**Comment by rafasoares** [comment]
You probably need to remove Halogen if you want to use Magnesium (they're both Sodium ports, so there's bound to be conflicts)
