### ISSUE TITLE
Add backup mod

### ISSUE THREAD

**Issue by quasarea** [czbuendel/EL2Test#156]
How could it make so far without any backup?

**Comment by FooterManDev** [comment]
I would very much enjoy a backup mod here, I have 12 worlds in the latest version of the pack, 9 of them have crashed, resulting in my inventory completely wiped, companions missing, Project MMO resetting my skills every few seconds, around a 3 hour backpedal, and my entire world ruined.

**Comment by dr3ams** [comment]
done in v.1.15
