### ISSUE TITLE
Impossible Quests

### ISSUE THREAD

**Issue by Eragoneq** [czbuendel/EL2Test#159]
Modpack Version: 1.14a/1.15

**Describe the bug**
Some of the quest dependencies cannot be fulfilled, as the quest node has no tasks.

**To Reproduce**
1. Open quest book
2. Unlock all quests in Industrial Foregoing path until and including plastic
3. Try to create a plant gatherer
4. There is no reward as the quest requires a dependency of "Farming", which has no tasks.

**Expected behavior**
All of the quest nodes should include some task.
This includes Industrial Foregoing quests and End Exploration, with other possibilities that I have not reached yet.

**Log Files**
No need for additional log files.

**Comment by dr3ams** [comment]
should be fixed in v 1.16
