### ISSUE TITLE
Quest no completing 

### ISSUE THREAD

**Issue by VoidGivenFocus** [czbuendel/EL2Test#160]
Modpack Version: 1.15

The quest for crafting the iron hammer and the diamond pickaxe do not complete upon crafting them

**Comment by lukeduncan-scot** [comment]
Just confirming, these are two separate quests yes?

- The iron hammer crafting quest fails to complete when it is crafted
- The diamond pickaxe crafting quest fails to complete when it is crafted

Thank you.

**Comment by dr3ams** [comment]
iron hammer crafting quest is tied to an advancement. complete it and it will autocompleted too
