### ISSUE TITLE
Raw Squid meat disabled

### ISSUE THREAD

**Issue by Shadow-player** [czbuendel/EL2Test#168]
Engineer's Life 2 - 1.16
If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**Describe the bug**
Raw Squid meat, needed for recipes is disabled.
Specifically Wabbity_VanillaFoodPantry.toml
exclude_squid_meat option is set to TRUE needs to be set to false to get drop.

Killing squids doesn't drop squid raw squid meat

**Expected behavior**
Killing squids should drop squid meat

**Comment by dr3ams** [comment]
fxd in 1.17
