### ISSUE TITLE
Picking up a labeled crate(Engineers Deco) with the Carry on- mod deletes Items inside.

### ISSUE THREAD

**Issue by Kleptomane** [czbuendel/EL2Test#18]
Jeah Title, i did lose some stuff kinda hurt, either dissable the ability to pick Labeled Crates up, or try to fix it.

**Comment by D0CTOR-ZED** [comment]
Thank you for bringing this to our attention.  It appears to be a conflict between Project MMO and Engineer's Decor.  Until that can be resolved, we wilk most likely have to remove the crates from the pack.

**Comment by czbuendel** [comment]
Newer versions of PMMO should fix this issue from my testing, should be included in next patch

**Comment by czbuendel** [comment]
1.01a fixes this issue with the new version of PMMO included.
