### ISSUE TITLE
Server crash when generating new chunks

### ISSUE THREAD

**Issue by Ronzan** [czbuendel/EL2Test#181]
Modpack Version: 1.17

Server crash.
No optifine.

**Describe the bug**
Server crashes generating new chunks.
A player that is out exploring (i.e. generating new chunks) cannot log back in, the server crashes when that player joins.
Other players, in "old" chunks, can join just fine.

**To Reproduce**
1. Exploring player joins the server
4. The server crashes

**Expected behavior**
The server should not crash.

**Screenshots**
No screenshots.

**Log Files**
Crash report: https://pastebin.com/jNNPHt5w
Latest log: https://pastebin.com/Fab3n3gd

I created an issue with Quark as well: https://github.com/VazkiiMods/Quark/issues/4002, but I wanted to post here as well, perhaps someone have seen this issue and knows what to do.

Thank you.
/Ronzan

**Comment by DoctorMage** [comment]
what happens if you use the same world seed in singleplayer

**Comment by Ronzan** [comment]
I haven't tried that - but, the world was started in singleplayer then moved to a server.
We moved on to another pack for now, so I guess I'll close this issue. Thank you for your time.

**Comment by DoctorMage** [comment]
AHHH i know what occured then  theirs a client side peformance mod sodium that for some reason effects terrain gen so if its removed as in you add the world to a server which does not have it world gen will change

I've had it break worlds before when test removing
