### ISSUE TITLE
Industrial Foregoing (To Industry and Beyond) quests bugged

### ISSUE THREAD

**Issue by arianmaykon** [czbuendel/EL2Test#185]
Modpack Version: 1.17

**Describe the bug**
Two quests are not opening for conclusion after the previous/required quests are done, this was first discussed on Discord here https://discord.com/channels/512339624627011586/779636129652932640/1058599712720162836 and the quests are the below (also visible in screenshot session):
1. Mining and Fabrication < Technology < To Industry and Beyond < Advanced Machine Frame;
2. Mob Griders < Technology < To Industry and Beyond < Advanced Machine Frame;

**To Reproduce**
1. Finish previous Industrial Foregoing quests to the point in the attached screenshot;
2. See the error where the quests does not open for conclusion;

**Expected behavior**
After the previous quests were concluded I expected that those 2 quests were available for conclusion also so I could follow up with the book next quests.

**Screenshots**
https://i.imgur.com/msAlyKp.png (also attached in the issue)
![msAlyKp](https://user-images.githubusercontent.com/40794/211610495-715c1424-267f-43db-8945-ee2cf4b6f0ee.png)

**Comment by dr3ams** [comment]
fixed in 1.18a
