### ISSUE TITLE
created a personal server and when in server terrain appears and then disappears 

### ISSUE THREAD

**Issue by JunkedE46** [czbuendel/EL2Test#187]
Modpack Version: 1.16.5 (Latest is not a version number)

i crated nd started a server then i load into world and ill be looking around and blocks nd terrain will appear and disappear while walking around or just looking around  
 [](url)
![2023-01-31_23 00 15](https://user-images.githubusercontent.com/47550894/215942343-cb53ec1d-b993-4552-bcfa-7bacaebc1966.png)
![2023-01-31_23 00 19](https://user-images.githubusercontent.com/47550894/215942345-43a1c26b-9579-4594-b498-4c9a803d8da8.png)
![2023-01-31_23 00 11](https://user-images.githubusercontent.com/47550894/215942349-1d194c05-5b29-4365-b8ef-aff99057f0ea.png)

**Comment by Joferorefoj** [comment]
I had the same problem, but when I deactivated the Chunk Multi-Draw in the advanced video settings, it disappeared.
