### ISSUE TITLE
Issue with loading or generating worlds [Engineer's Life 2]

### ISSUE THREAD

**Issue by Dimitry-Blitzbrieg** [czbuendel/EL2Test#19]
I'm currently having issues trying to create a world so i can play using this modpack on the latest version "1.0" i even tried the world preview and that doesn't load either.

my pc specs are:
AMD Ryzen 7 3700X 8 core
32GB DDR4
Nvidia GeForce RTX 2070 Super
Minecraft is On a dedicated Gaming drive as OS SS-Disk has very limited space  [Samsung QVO 860 2TB SSD]
I do put aside 12GB for Minecraft so it has more than enough for running many modpacks.

as the world doesn't load I've been having to force quit the session though the Task Manager, I've tried loading up a world multiple times even at reduced ram [6gb]. still having the same issue.

**Comment by Polapawow** [comment]
I have the same problem. I can't load the afternoon world.

**Comment by Dragonsmen83** [comment]
Same issue just installed v1.0 and it freezes on world loading from starting the world or in pregen

**Comment by D0CTOR-ZED** [comment]
This is a known issue with using the CurseForge launcher.  I recommend switching to GDLauncher (https://gdevs.io/).  If you have migrated your minecraft account to a microsoft account, you may need to use their beta (https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.1.0-beta.2).
