### ISSUE TITLE
Can't harvest hemp fibers from hemp plants

### ISSUE THREAD

**Issue by caseyjfer** [czbuendel/EL2Test#20]
Industrial hemp plants are growing as expected, but when they reach 2 tiles tall and I break them, they do not drop anything (seeds or fibers). I've tried breaking them with a bare hand, a hoe, and an axe.

**Comment by czbuendel** [comment]
That is an issue with No Tree Punching that we have a fix coming for in the next update. For the time being you should be able to use a Butchers Axe from Vanilla Food Pantry to harvest it or any vanilla sword.

**Comment by aikainnet** [comment]
A knife is what is needed btw.

**Comment by czbuendel** [comment]
This is fixed in 1.01a. You should be able to harvest hemp with almost anything now, even by hand.
