### ISSUE TITLE
Multiplayer Quest Sharing

### ISSUE THREAD

**Issue by Pinguin34** [czbuendel/EL2Test#26]
Hi. when we played in Multiplayers, all quest are induvidually and we can't create a FTB party to synchronize quest

**Comment by czbuendel** [comment]
This isn't an issue. FTBQuests/FTBTeams doesn't have team shared questing implemented in 1.16. As soon as it is released, and it is stable we will include it in the pack. Closing and pinning this for now. Will update when the update including it is released.

**Comment by enderger** [comment]
It's in as of the previous release of FTBQuests.

**Comment by czbuendel** [comment]
We know there are versions of FTBQ with quest sharing. As of our last check it is still not stable and will be included in a pack update when it releases in a stable enough manner. 
It also removes any existing quest progress from existing saves so it is being saved for large update that will require restarting a game.
