### ISSUE TITLE
Axe can't break Charm's Woodcutter (but a Pickaxe can)

### ISSUE THREAD

**Issue by ghost** [czbuendel/EL2Test#27]
Axe-type tool, which supposed to break Charm's woodcutter, the break process won't progress when breaking the Block, as seen in these image:

trying to break using Tetra Modified Steel Axe :
![2021-04-17_22 31 16](https://user-images.githubusercontent.com/60312923/115118886-b5ad1d00-9fcf-11eb-9c03-0888baf1bb44.png)

trying to break using Mattock from No Tree Punching
![2021-04-17_22 31 12](https://user-images.githubusercontent.com/60312923/115118927-fe64d600-9fcf-11eb-9a1f-5c89c8d1dd1f.png)

trying to break using Vanilla Iron Axe
![2021-04-17_22 32 18](https://user-images.githubusercontent.com/60312923/115118942-15a3c380-9fd0-11eb-8733-335b331a3ce9.png)

but when i tried to use Tetra Modified Diamond Pickaxe (a non-axe tools), the breaking process works
![2021-04-17_22 32 45](https://user-images.githubusercontent.com/60312923/115119009-77fcc400-9fd0-11eb-9239-e0c3c38f6286.png)

**Comment by czbuendel** [comment]
I will look into this.

**Comment by D0CTOR-ZED** [comment]
Thank you for your report.  This can been identified as a mod interaction between the Charm woodcutter and Natural Progression.  We are attempting to get the issue fixed but it isn't something we can do without one of the mods fixing their end.  For now, a workaround has been created for the next update.  And, as you pointed out, using a pick is a workaround for now.

**Comment by czbuendel** [comment]
As of 1.02 the placeholder solution for the issue has been put into place by Zed that should allow the woodcutter to be broken with any axe. Closing this for now.
