### ISSUE TITLE
Mr. Freeze

### ISSUE THREAD

**Issue by loadstones** [czbuendel/EL2Test#28]
Modpack Version: EL2-1.16.5-1.01 (Latest is not a version number)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**Describe the bug**
I've been playing this pack for 25+ hours and all of a sudden no matter what biome I am in water freezes and snow forms. I have stripped naked except for a sleeping bag and traveled a good 15 to 20 biomes away from my base and it keeps following me. I had looted boots with frostwalker yesterday, but deleted them in the inventory trash, I never wore them.

Update: Created a test world and the problem followed me there. Copied savegame, deleted pack and reinstalled. Loaded save and has worked fine for last 10 minutes. will update again if it returns.

**Comment by czbuendel** [comment]
I may close this for now seeing as you have it resolved but if it crops up again just come back and @ me here and I will reopen and look at it.

**Comment by loadstones** [comment]
I played about 8 hours today and everything seems good. Thanks

**Comment by czbuendel** [comment]
Just let us know if it crops up again. 👍🏼
