### ISSUE TITLE
Disappearing Items and Skill Reset

### ISSUE THREAD

**Issue by moonshane95** [czbuendel/EL2Test#29]
Modpack Version: 35.1.28 (Latest is not a version number)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**Describe the bug**
chest, bed and character disappear after 5 minutes of play. the abilities of the project mmo, specifically agility, are reset when I reach the surface from the mine.

**Comment by czbuendel** [comment]
35.1.28 is not a modpack version.
Also if you are going to make issue reports name them properly, these aren't "jokes".

What launcher are you using?

**Comment by D0CTOR-ZED** [comment]
You are experiencing a known issue from an earlier version of Project MMO.  Update to a non-beta release version to avoid these issues.  Updating to the most recent version should be done when experiencing issues.  If an issue exists in the most recent version, then please feel free to submit an issue.
