### ISSUE TITLE
Farming XP penalty from breaking grass

### ISSUE THREAD

**Issue by mindsolve** [czbuendel/EL2Test#30]
Modpack Version: `EL2 - 1.01a [1.16.5]` (from CurseForge)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.
- No Optifine installed

**Describe the bug**
- When breaking (Vanilla) grass, I get `0.60` XP substracted from my farming XP.
Sometimes (very rarely) I also get the PMMO XP message `+-0.60 Farming`.
This behaviour seems to be independent from the used tool, as at least hand, knife and axe make no difference.

**To Reproduce**

1. Enable XP list (default `left alt`)
2. Break any vanilla minecraft grass block
3. Observe negative XP change for farming

**Expected behavior**
- No farming XP penalty should be applied.

**Screenshots**
Before:
![before-breaking](https://user-images.githubusercontent.com/24863329/115156513-da170100-a084-11eb-9ec1-49e4c316a6c4.png)
After:
![after-breaking](https://user-images.githubusercontent.com/24863329/115156558-0d599000-a085-11eb-99db-78f8084d576e.png)

**Log Files**
If the pack is crashing please provide the latest.log from the logs folder of your instance. Use https://gist.github.com to create a link to share the log.
- No log lines from/during the event were found, neither in debug.log, nor latest.log.

**Comment by czbuendel** [comment]
I derped when I made the pmmo break xp list and accidentally applied the values for grass blocks to the grass. I fixed that with https://github.com/Engineers-Life/EL2/commit/1815af20a1e2d56f9eaf03811072b043f354b67f.

**Comment by czbuendel** [comment]
You can download this file and drop it into the pmmo folder in the config folder and let it overwrite the exisiting file.
[xp_value_break.zip](https://github.com/Engineers-Life/EL2/files/6332376/xp_value_break.zip)

**Comment by mindsolve** [comment]
Absolutely marvellous! I just tested it, works beautifully now :)
Thank you so much for your quick response & have a wounderful day!
