### ISSUE TITLE
Items and blocks stacking separately after placing in the world

### ISSUE THREAD

**Issue by raz818** [czbuendel/EL2Test#37]
Modpack Version: 1.02 (Latest is not a version number)

**Describe the bug**
After updating to the newest version of the pack, when I place a block from an existing stack in my inventory  and break that block, the block item in my inventory will no longer stack with the original stack

**To Reproduce**
1. Have a stack of blocks in your inventory. Number of blocks does not matter
2. Place a block from that stack in the world.
3. Break the block
4. Pick up dropped item

**Expected behavior**
Blocks should stack with other blocks of same type

**Screenshots**
Original stack of sand and stack of strange behaving new sand
![Screenshot 2021-04-25 173711](https://user-images.githubusercontent.com/8808682/116011939-18fd0780-a5ed-11eb-8019-1169eee343a7.png)

Stacks after breaking and picking up block
![Screenshot 2021-04-25 173809](https://user-images.githubusercontent.com/8808682/116012006-8ad55100-a5ed-11eb-89fd-e50a2ac9a508.png)

**Comment by czbuendel** [comment]
Tracking this down currently.

**Comment by czbuendel** [comment]
@raz818 What did you use to break the sand?

**Comment by raz818** [comment]
@czbuendel I used my hand

**Comment by raz818** [comment]
After reverting to 1.01a the issue persists

**Comment by czbuendel** [comment]
Delete the events.zs file from the script folder in your instance.

**Comment by raz818** [comment]
That seems to have fixed it. Although any glitched items that existed in my inventory after I deleted that file still acted in the glitched way, once I place every single one of those items into the world and broke them, everything returned to normal.
Thank you for the speedy response!

**Comment by czbuendel** [comment]
Yeah if you threw them onto the ground they will restack properly. Will probably do a hotfix to correct this. Pinning it as well.

**Comment by czbuendel** [comment]
1.02a fixed this.
