### ISSUE TITLE
Add Dictionary and Binder to Akashic Tome Whitelisted phrases

### ISSUE THREAD

**Issue by DatenThielt** [czbuendel/EL2Test#38]
Currently The Akashic Tome will not accept certain books, (E.G Animal Dictionary and Buddy Binder) this is due to the config not accepting Dictionary and potentially binder.

Add the word Dictionary and Binder to the config's whitelist, binder is not huge since it has additional functionality but is still potentially a book!

More QOL than a bug :)

**Comment by czbuendel** [comment]
Added the functionality with this commit. (https://github.com/Engineers-Life/EL2/commit/45fd90bb730b00e34d722fc2706f921945365329)

Did a bit of testing with the binders and you can add only a single one to the tome.
