### ISSUE TITLE
In the "First Steps" questline, the sleeping bag and hammock items are called "OR Filter"

### ISSUE THREAD

**Issue by 5il3nc3r** [czbuendel/EL2Test#39]
Modpack Version: 1.02a

**Describe the bug**
The name if the items needed for the Sleeping Bag and Hammock quests are just called "OR Filter"
Note: Actual item still works to complete the quest

**To Reproduce**
1. Open the questbook
2. Go in the First Steps questline
3. Open either the "Alternate Sleeping Arrangements" or "Laying out in the Sun" quests
4. Notice the tooltip name given for the Sleeping Bag or the Hammock

**Expected behavior**
The tooltip name should be of the item itself
![image](https://user-images.githubusercontent.com/10393041/116116926-b3128d80-a689-11eb-8909-5805ac5e83ff.png)

**Comment by czbuendel** [comment]
Fixed with (https://github.com/Engineers-Life/EL2/commit/5b3eb84f41b613da9627d73b3e1d58cb21ec8d1f).
