### ISSUE TITLE
Bunch of Berries Recipe

### ISSUE THREAD

**Issue by czbuendel** [czbuendel/EL2Test#40]
![image](https://user-images.githubusercontent.com/23238026/116123845-2071ee80-a689-11eb-8996-e6e017e48ea8.png)
Look at fixing this recipe conflict.

**Comment by D0CTOR-ZED** [comment]
Changed Simple Farming dye recipes to only needing one berry.  It's more consistent with other item to dye recipes.  Almost went with two berries, but with farmable flowers in the pack, dye isn't meant to be hard to get.
https://github.com/Engineers-Life/EL2/commit/21f8f232d7378a40418a374018a0e5688a8109bb
