### ISSUE TITLE
Unable to craft automatic beehives because campfires are required.

### ISSUE THREAD

**Issue by Decycle** [czbuendel/EL2Test#41]
Modpack Version: EL2-1.16.5-1.01a

**Describe the bug**
In order to craft automatic beehives in automatic bees mod, a campfire is needed in the recipe. However, there are currently noway of crafting campfires items.

**To Reproduce**
1. Check the recipe of automatic beehive using JEI
2. Found out a campfire is required, which is impossible to craft. 

**Expected behavior**
The recipe for automatic beehives should be altered, or maybe add a recipe for campfires.

**Comment by czbuendel** [comment]
Update to 1.02a. Campfires have been replace with soul campfires.
