### ISSUE TITLE
Add recipes for certain items that currently have no use

### ISSUE THREAD

**Issue by 5il3nc3r** [czbuendel/EL2Test#42]
Currently, most mob heads have no uses at all (except Dragon Head, Wither Skeleton and, technically, the Creeper head (for a Banner))

**Describe the solution you'd like**
Add a recipe to craft mob heads into the mob's basic drop. Zombie Head -> Rotten Flesh, etc.

**Describe alternatives you've considered**
Also maybe include a recipe for Frozen Flesh to be cooked into Rotten Flesh, since it's current only use is to be eaten

**Additional context**
This suggestion is mostly to eliminate "dead end" items.

**Comment by D0CTOR-ZED** [comment]
Some practical uses might be nice, but just a quick fyi.  You can put mob heads on note blocks to change the sound they make.  I'm not suggesting that you bury a note block under someone's door rigged to a pressure plate to make a creeper noise every time they open their door, just saying it is possible.

**Comment by D0CTOR-ZED** [comment]
The mob heads are generally considered trophy pieces.  There are no plans to give them greater use at this time.  It may happen at some later date, but not likely.  As far as frozen flesh, it should have the same uses as rotten flesh in the next update.
