### ISSUE TITLE
Able to duplicate glass with the Bottle 'o Enchanting recipe

### ISSUE THREAD

**Issue by 5il3nc3r** [czbuendel/EL2Test#48]
Modpack Version: 1.02a

**Describe the bug**
It only costs 250mB of Essence to craft a Bottle 'o Enchanting; but the recipe to make Essence from said bottle also gives 12 glass shards, which is enough to make 3 Glass Blocks (aka 3 more Empty Bottles)

Additionally, there's a recipe for 1 Bottle in the Squeezer to make 12 Glass shards which, again, is enough for 3 full Glass blocks.
So free glass.

**To Reproduce**
1. Get 1 Empty Bottle and Shift-Right-Click while you have levels, to create a Bottle 'o Enchanting
2. Place the Bottle in a powered Squeezer
3. Craft the glass shards into glass blocks, and into bottles
4. Notice that you got 3 Empty Bottles from one bottle

**Expected behavior**
Since you normally get 3 Bottles from 3 Glass, then setting the Squeezer recipe to give back the 250mB of Essence, and 4 Glass Shards instead of 12.
Also, make the Dissolution Chamber recipe for Bottle 'o Enchanting to cost 250mB of Essence and an Empty Bottle, to get equivalence.

**Comment by D0CTOR-ZED** [comment]
Quantity of glass shards fixed for next release: https://github.com/Engineers-Life/EL2/commit/2a73988beaa562889b66b035e258a027a905a923

**Comment by D0CTOR-ZED** [comment]
Added a bottle to the recipe to make a bottle of enchanting for next release: https://github.com/Engineers-Life/EL2/commit/34ab37deb0baa26ae0384ac8716d19b21f9a491e
Thank you for your feedback.
