### ISSUE TITLE
The "Cooking for Engineers" in the Outstanding in a Field questline isn't linked to the one in Culinary Engineering

### ISSUE THREAD

**Issue by 5il3nc3r** [czbuendel/EL2Test#51]
Modpack Version: 1.02a

**Describe the bug**
Normally, quests with the "Gear" outline are meant to unlock the linked quest in a different questline, however, I was able to complete the "Cooking for Engineers" starter quest in Culinary Engineering before gaining access to the equivalent quest in Outstanding in a Field, which I believe is meant as the precursor quest to get started with Cooking for Blockheads

**To Reproduce**
1. Start a New Game and disregard any progress in the "Outstanding in a Field" questline
2. Craft the "Cooking for Blockheads 1" book
3. Notice that the starter quest in the "Culinary Engineering" is completed
4. The related quest in "Outstanding in a Field" is still disabled and uncompleted

**Expected behavior**
User should only be allowed to start in "Culinary Engineering" after having reached and completed the related quest in "Outstanding in a Field"

**Screenshots**
Screenshots taken at the same time, to show that one is completed but not the other.
![image](https://user-images.githubusercontent.com/10393041/116408960-618d0e80-a801-11eb-9335-469928b68aec.png)
![image](https://user-images.githubusercontent.com/10393041/116409004-6a7de000-a801-11eb-8a96-45e55ab028a0.png)

**Comment by czbuendel** [comment]
It really isn't quite a "bug" but a design decision that we ended up making. None of the gear quests that start chapters are truly gated to the completion of the same quest further in earlier chapters. This is to make the quest book more of a guide for best progression, not of required progression.

**Comment by czbuendel** [comment]
Actually decided to change this singular quest, I made it smaller to signify that it isn't a major branch into the next chapter.
(https://github.com/Engineers-Life/EL2/commit/94c91ef85fa6b35e927334a145d83765cdd26140)
