### ISSUE TITLE
Quarks chests aren't craftable

### ISSUE THREAD

**Issue by TheNoobyTalker** [czbuendel/EL2Test#55]
Modpack Version: 1.02a  

Optifine isn't installed in the pack currently

When i wanted to craft some quark spruce chests via the custom recipe, the recipe didn't accept the vanilla chest even though it was listed as an acceptable chest to be used in the recipe. I'm not sure why, but it also doesn't accept modded ones.

1. Get some spruce planks and a chest of your choice
2. Put it in a crafting table 
That should be showing the described recipe issue.

I thought that the recipe should be working fine, but turned out that it wouldn't be the case.

![2021-04-30_16 21 25](https://user-images.githubusercontent.com/56347537/116708652-360c4e80-a9d0-11eb-9092-00e4191cb967.png)
It's clearly showing that a vanilla Chest is acceptable.

![2021-04-30_16 21 29](https://user-images.githubusercontent.com/56347537/116708655-36a4e500-a9d0-11eb-94b6-eae90064be28.png)
The recipe is showing that it's able to be crafted, indicated by the clickable plus button.

As it's a recipe issue there's no crash log.
I would put the Crafttweaker Log in, but it would be too big for this form.

**Comment by D0CTOR-ZED** [comment]
Sorry, due to a slight error, the recipe requires a trapped chest in the center.  Should be fixed for the next release.

**Comment by D0CTOR-ZED** [comment]
The script is now fixed for the next release.
https://github.com/Engineers-Life/EL2/commit/d0ffbd84284854e398eb9404cf01ce230465fb1f

**Comment by TheNoobyTalker** [comment]
Ok thanks for clarification
