### ISSUE TITLE
Changes to the loot table of some mobs

### ISSUE THREAD

**Issue by MicanJoe** [czbuendel/EL2Test#66]
Modpack Version: 1.01a (altough it should be the same as for 1.02a)

**Describe the bug**
The loot-table for horse and squid meat defaults to the one from simple farming causing problems with the crafting of squid related food from VFP and also wont work toward the iron stomach achievment from VFP (its an achievement that gives you an unobtainable item). Phantom meat seems to be also missing from the phantom's loot table (which is required for the iron stomach achievment).

**To Reproduce**
Kill squids, horses and phantoms

**Expected behavior**
For the aforementioned mobs to have their respective VFP meat drops plus checking on the simple farming if any recipe is compatible with just the simple farming meats
**Screenshots**
NIL

**Log Files**
NIl

**Comment by D0CTOR-ZED** [comment]
The drops for the squids and horses will be fixed in the next update.  The phantom meat drop is disabled in the config.  It may remain disabled for the pack, but you could choose to enable it for yourself.
