### ISSUE TITLE
Undead bees don't spawns

### ISSUE THREAD

**Issue by Gr00ze** [czbuendel/EL2Test#72]
Modpack Version: 1.02a (Latest is not a version number)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.
Done,  the issue still occurs.

**Describe the bug**
Undead bees don't spawns.

**To Reproduce**
1. Place unlit and empty beehives
2. Wait a lot of nights
3. Check hives
4. See error: they still empty.

**Expected behavior**
undead bees spawn.

**Screenshots**
No need, i think

**Log Files**
If the pack is crashing please provide the latest.log from the logs folder of your instance. Use https://gist.github.com to create a link to share the log.
No

**Comment by czbuendel** [comment]
I re-enabled them with this (https://github.com/Engineers-Life/EL2/commit/769554d2af274a2dcd295cae5becdc5efb375a3f) I will see if any issues arise and see if we keep it in following the next update.
