### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Ari0ner** [czbuendel/EL2Test#73]
Modpack Version: 1.02a

Uninstalled Optifine, crash still exists

**Describe the bug**
Game crashes while wandering around

**Log Files**
latest log
https://gist.github.com/Ari0ner/9a2bfce9d4e29d68553ebe3ed6b638f2
crash report
https://gist.github.com/Ari0ner/80cfc2c89089c184bcace9831af5da35

Seems like its some quark-simplefarming problem

**Comment by czbuendel** [comment]
This is a long standing issue with Simple Farming. Nothing we can do about it currently. https://github.com/cweckerl/simplefarming/pull/139 The issue I believe was fixed here so when the mod actually updates we will update the pack.
