### ISSUE TITLE
Enchantment Duping

### ISSUE THREAD

**Issue by MisterZam** [czbuendel/EL2Test#75]
Tried enchanting a tetra tool in the IE enchantment factory. Decided to rip the enchant using the enchantment extractor because I didnt like the enchantments. I was able to get the enchants but ut didnt seem to remove the enchants from the tool. Thus enchantment duping happened

**Comment by czbuendel** [comment]
Not a modpack issue, report it to the Industrial Foregoing or Tetra Devs.
