### ISSUE TITLE
Alex's Mobs Quests

### ISSUE THREAD

**Issue by czbuendel** [czbuendel/EL2Test#78]
Look into a chapter for alex mobs stuff possibly.

**Comment by czbuendel** [comment]
It doesn't appear that Alex's Mobs has advancements so I will need ideas on quests for this if this is decided to go further.

**Comment by Drakoflame** [comment]
here's an idea: "Get the drop on a Dropbear"

Those mf's scarry... I legit screamed two times because of them... Piglins also hate them, which is good to know...

**Comment by D0CTOR-ZED** [comment]
In the absence of advancements, quests could either be based on drops:
https://github.com/Alex-the-666/AlexsMobs/tree/main/src/main/resources/data/alexsmobs/loot_tables/entities (note that some entries are blank and I would imagine that some drop items not unique to the mod)
Or simple kill count quests (may just for mobs that either don't have a unique drop as well as ones that might have that unique drop be very rare).  As far as overall structure of the quest page, I could see making logical sections in a manner similar to biological classifications.

**Comment by czbuendel** [comment]
Initial work in (https://github.com/Engineers-Life/EL2/commit/29c68067e6e55abc5a64099d50d33f7614a6c4d5)
![image](https://user-images.githubusercontent.com/23238026/119462693-a162eb00-bd06-11eb-96aa-20646e2da123.png)
Logic:
Tree: Top is flying animals, working the way down is tree oriented or climbing animals

Ground: Ground dwelling animals working their way down as roots, underground animals start beneath the surface. A "rock" or "hill" for the guster. Slight dropping towards the right for the shore.

Far right: water based animals, distinction by all quests following the same progression line direction as "waves".

Bottom: Nether animals on the left with the land animals on a "ground level" and those that fly above them. Right group are the few End creatures.

**Comment by czbuendel** [comment]
Ok final push of actual quests with (https://github.com/Engineers-Life/EL2/commit/056bdac87ee12eac772e74523276e4fab3338063)

Layout subject to change but doesn't need to be tracked here.
