### ISSUE TITLE
Change the rewards for the To Boldly Go -> Conduit quest

### ISSUE THREAD

**Issue by 5il3nc3r** [czbuendel/EL2Test#79]
if the user never got/made a Trident, completing the Conduit quest will give them one, which will complete the Trident quest.
I don't believe it's a good thing that a quest's rewards complete other quests.

**Describe the solution you'd like**
Simply changing the rewards of the Conduit quest to something else (that isn't a quest requirement)

**Describe alternatives you've considered**
Since the quest is the last in it's (short) line of quests, and considering the topic of the quest, I think maybe an enchanted book for Aqua Affinity or Depth Strider.
![image](https://user-images.githubusercontent.com/10393041/118560688-e2239880-b737-11eb-90ab-37a9c4343768.png)

**Comment by czbuendel** [comment]
Changed in (https://github.com/Engineers-Life/EL2/commit/6450028eefbdce63a3bf2c6569f2fd0ab4b0cb55)
