### ISSUE TITLE
Bug with the woodcutter when you place inside it spruce that cause a game crush

### ISSUE THREAD

**Issue by Quilbij** [czbuendel/EL2Test#80]
Modpack Version: 1.03

**Describe the bug**
When you place spruce wood in the woodcutter when you scroll the options till the end the game crush if you select an empty icon

1. Take a woodcutter
2. Place spruce wood in it
3. Scroll till the end
4. Select the empty option below the framed hammer

**Expected behavior**
The game freeze and afrter a while it crush

![Base Profile Screenshot 2021 05 17 - 23 50 52 92](https://user-images.githubusercontent.com/84354345/118561826-e8cc0300-b76b-11eb-97aa-39080edf6287.png)

**Log Files**
[crash-2021-05-17_23.39.53-client.txt](https://github.com/Engineers-Life/EL2/files/6497102/crash-2021-05-17_23.39.53-client.txt)

**Comment by czbuendel** [comment]
Is fixed with (https://github.com/Engineers-Life/EL2/commit/e2f0a4375c078f1103ae3fd4f74bfbdb1148ec4c)
