### ISSUE TITLE
Change the way IF items are disabled

### ISSUE THREAD

**Issue by czbuendel** [czbuendel/EL2Test#85]
Current way of disabling the items leads to a lot of log spam

**Comment by czbuendel** [comment]
Maybe should try it through CT instead of by config

**Comment by D0CTOR-ZED** [comment]
Disabling through the config also generates an error message in their in-game manual.  Disabling through other means may leave inaccurate entries in the manual but that could be preferable to generating errors.

**Comment by czbuendel** [comment]
Log spam cleaned up and fixed with (https://github.com/Engineers-Life/EL2/commit/12ad6b77debb8d6fd2d10da50ed28d1646eaec71)

**Comment by czbuendel** [comment]
The manual works much better and isn't missing entries as far as I can tell anymore.
May want to look into how to change the manuals.

**Comment by czbuendel** [comment]
Probably just leave it as it is, lists a bunch of items that don't exist in the pack.
