### ISSUE TITLE
Engineers Crafting Table added to Woodcutter for all woods

### ISSUE THREAD

**Issue by czbuendel** [czbuendel/EL2Test#87]
Shouldn't be in woodcutter.

**Comment by D0CTOR-ZED** [comment]
Fixed woodcutting logic.
https://github.com/Engineers-Life/EL2/commit/85d7dc165fa569dc9e2464ab2e202545d5f85eba#diff-161e87ca526b407c924bf50990d7811a3c25b202a22d042e4bf7453532f6714c
