### ISSUE TITLE
'Big Book of Bees' Quest "No Valid Item" (Not bug, sorry. Feel free to delete. I just can't read.)

### ISSUE THREAD

**Issue by Ghost8909** [czbuendel/EL2Test#88]
Modpack Version: 1.16.5 v1.03

Disclaimer: I do, in fact, have Optifine installed, as well as Better Animals Plus, and Curios Armor Stand.

**Describe the bug**
When looking in the available quests, clicking on Tasks for "Big Book of Bees" states that no valid item is available, and to report this to a modpack dev.

**To Reproduce**
1. Go to Bee Productive
2. Click on Big Book of Bees
3. Click on book in Tasks

**Expected behavior**
Other quests appear to give the recipe for the item in question. I assume this one is intended to as well.

**Screenshots**
![NoValidItems](https://user-images.githubusercontent.com/11306942/119291580-b2373200-bc1c-11eb-9798-84e1edaea18f.png)

**Comment by czbuendel** [comment]
Literally read the note in the quest.
