### ISSUE TITLE
Missing VFP recipes from CFB crafting table

### ISSUE THREAD

**Issue by czbuendel** [czbuendel/EL2Test#91]
Things like chocolate syrup are missing.

Probably anything using the syrup base.

**Comment by czbuendel** [comment]
Caffiene powder required drying agent, which isn't in anymore.

**Comment by D0CTOR-ZED** [comment]
> Caffiene powder required drying agent, which isn't in anymore.

Drying agent is obtained by mining sand with a hand rake.  It's in the quest book.

**Comment by czbuendel** [comment]
Fixed in (https://github.com/Engineers-Life/EL2/commit/adbf7a003c4f6e9c10d310afe5370084788dfd60#diff-b17ea74bd787c8ae286aa3d1246bd933c9ee12c4d09fed6e142aeac028a94277)
