### ISSUE TITLE
Feature Suggestion: Cactus Damage

### ISSUE THREAD

**Issue by desagas** [czbuendel/EL2Test#94]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Life when you punch fire, you get burned for a second, or when you munch a wrong tooled block with your fists, I think the same should be true for punching cactuses without an axe, if it is possible.

**Describe alternatives you've considered**
As is.

**Additional context**
Just living near a desert taking no pain from harvesting the cactuses, thinking about all the other random times I take damage.

**Comment by czbuendel** [comment]
Unfortunately we have no control over the blocks that cause damage, It may be a good suggestion to make the the Natural Progression dev though. https://www.curseforge.com/minecraft/mc-mods/natural-progressions
