### ISSUE TITLE
Distillation tower causing crashes

### ISSUE THREAD

**Issue by Bdixe** [czbuendel/EL2Test#95]
Modpack Version: 1.03

Is repeatable without Optifine

Running the distillation tower causes the game to crash, and the tower seemingly will not input fluids into pipes (unsure if these are related)

log: https://gist.github.com/Bdixe/35608e33c92fa8483c1acc3459bff526

**Comment by czbuendel** [comment]
From the log file I am guess you are trying to use Quark pipes? 
They only move items, not fluids.

**Comment by Bdixe** [comment]
I have quark pipes for the bitumin output, not the fluids, although that does remind me I wasn’t having crashes until i installed the quark pipes so i could try deleting those.

**Comment by czbuendel** [comment]
Ok cool, just wanting to make sure. I brought it up to the IP dev and they were able to replicate it but aren't quite sure what is causing it.

**Comment by czbuendel** [comment]
This is fixed with the newest version of IP. https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum/files/3384353
