### ISSUE TITLE
Standing on Conveyor Belts Crashes SP and DCs MP

### ISSUE THREAD

**Issue by mcgeekster13** [czbuendel/EL2Test#98]
Modpack Version: 1.0.4

**Describe the bug**
Standing on any conveyor belt (or near a vertical)  from Immersive Engineering results in a CTD if in single player and a disconnect if in a multiplayer server.  Covered conveyor belts appear to work as intended.  Conveyors still transport items as expected.  Crashes only occur when stepped on by a player entity.

**To Reproduce**
1. Place a conveyor belt.
2. Walk on, jump onto, approach it in any way.
3. Crash

**Expected behavior**
I expected to be moved in the direction the conveyor belt was moving.

**Log Files**
https://gist.github.com/mcgeekster13/342084e5e771b0275b08428080f43aee

**Comment by czbuendel** [comment]
Please check the respective mods github before posting here.
https://github.com/BluSunrize/ImmersiveEngineering/issues/4833
Nothing we can do about it at this time.

**Comment by czbuendel** [comment]
I will post here when the issue is fixed.

**Comment by NatheArrun** [comment]
Seems like this issue is localized to the 5.0 version of IE, so temporarily downgrading to 4.0 (and all the IE addons as well) allowed me to fix this with the loss of only the Circuit Table and Logic Unit from the world.

**Comment by czbuendel** [comment]
Yeah don't recommend that.
You would break many quests not to mention Immersive Petroleum.

**Comment by czbuendel** [comment]
It has been fixed with the newest release of Tetra, 3.12.0. You can update the mod yourself and it will be included in the next release version.
